### ISSUE TITLE
TLS/QUIC Support

### ISSUE THREAD

**Issue by thavlik** [TES3MP/openmw-tes3mp#573]
I'm not finding much on TLS support, so my assumption is that TES3MP uses unencrypted UDP datagrams, exposing everyone to man-in-the-middle attacks. I am currently using a VPN to network with buddies, which automatically handles the encryption between players' machines. However, using a VPN is decidedly less appropriate when hosting a dedicated server. Ideally, the game itself implements TLS.

This issue is intended to start discussions about implementing support for [QUIC](https://en.wikipedia.org/wiki/QUIC) or a comparable secure transport protocol. There are multiple QUIC implementations for C++ that appear mature, but I have only personally used Rust's [quinn](https://github.com/quinn-rs/quinn), and with great success.

The datagram send/receive API for QUIC is designed to mirror that of UDP, ostensibly making it straightforward to add QUIC support where UDP already exists. I have no familiarity with TES3MP or OpenMW's codebases, so it's unclear to me if that holds true here.

Thoughts?

**Comment by davidcernat** [comment]
Using secure connections in the network library used by TES3MP (a slightly modified variant of RakNet) is relatively straightforward:

http://www.raknet.net/raknet/manual/secureconnections.html

However, given that it is an unfinished hobbyist project with a small audience, the additional bytes added to each packet have not been worthwhile thus far.

QUIC is similar to TCP in that it is focused on reliable, ordered delivery of data and would not provide benefits to TES3MP, as it is not designed to be used for this kind of multiplayer game. The following comments sum the situation up well:

https://news.ycombinator.com/item?id=18519459
https://news.ycombinator.com/item?id=18519432
https://www.reddit.com/r/networking/comments/gjiohd/question_about_quic_viability_for_multiplayer/fqlktkn/

The idea of switching to QUIC just because it's a new technology — regardless of the fact that it isn't us — doesn't make a lot of sense, so this isn't the kind of issue that should be opened.

**Comment by thavlik** [comment]
>Using secure connections in the network library used by TES3MP (a slightly modified variant of RakNet) is relatively straightforward:
Is this implemented? RakNet absolutely looks appropriate, but its appropriateness does not necessarily mitigate that of QUIC. If the project author prefers RakNet, imo that's reason enough to prefer it. However, I feel it necessary to respond to the rest of your reply.

> It would not provide benefits to TES3MP, as it is not designed to be used for this kind of multiplayer game. The following comments sum the situation up well:
This comment merely demonstrates ignorance to the many knobs and dials of QUIC. QUIC is more than capable of providing a smooth experience for soft real-time gaming, and can be configured such that its performance is negligibly lower than UDP. I have used QUIC extensively, and to say it is narrowly focused on reliable/ordered delivery is a gross simplification. After reading into RakNet, it is not obvious that its *performance* would deviate from a similarly configured QUIC setup. RakNet has significant features outside of performance which justify its use, but I would be surprised if there was a measurable performance difference between RakNet and correspondingly configured QUIC.

> The idea of switching to QUIC just because it's a new technology — regardless of the fact that it isn't used in this kind of game — doesn't make a lot of sense, so this isn't the kind of issue that should be opened.
In case it wasn't clear, I **was** considering volunteering my time to implement *some* sort of encryption. QUIC was merely an opening suggestion, and this issue was dedicated to a broader discussion about secure transport.

There is a subtle display of hostility here that is, frankly, inappropriate. You are making a straw man argument suggesting 1.) the only reason I'd suggest it is because QUIC is, according your perception, "new technology" (though this is not the case) and 2.) this idea is so far beyond practical as to be nonsensical. You even felt it necessary to subtly scold me for even opening the issue. This is not a good look.

It's rather unfortunate because I've had a good time with TES3MP and was eager to make various contributions - secure transport was definitely not the only one. It would appear TES3MP is, yet again, a project ran by a passive-aggressive individual who is less interested in hosting a productive conversation and more in making himself look good by dunking on potential contributors.
